### ISSUE TITLE
Unnecessary GOOGLE_APPLICATION_CREDENTIALS placeholder

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#40]
If you follow the gcloud init and auth steps as documented, bigquery.py will find the credentials that are setup using those commands.  But now there is a hard-coded env var to override that.  I think that change should be reverted.  If there is some good reason for adding this in the code maybe it needs more explanation for when to use it and probably should be commented out by default so that the basic flow still works.

+# Specify path to generated environment variable json for project 
+os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "#path_to_json_credential_file"

**Comment by markstur** [comment]
@tonanhngo @nimicent

**Comment by nimicent** [comment]
Hey Mark! If you think it could be an additive per the README and commented out so it can be enabled as a possible solution if issues occur (as I found it to be) I think that is valid. I am sure others could encounter both scenarios. I did the instructions to a T since I had never used Gcloud before and it still was an issue. I'll make the changes. @markstur @tonanhngo

**Comment by markstur** [comment]
@nimicent That would be great.  Yes, I know it worked as it was -- unless I need to update some google thing that breaks it.  I agree your suggestion might help others.

**Comment by markstur** [comment]
Fixed in #41
